/****** Object:  Database [CinderellaCore]    Script Date: 2/8/2021 20:27:14 ******/
CREATE DATABASE [CinderellaCore]  (EDITION = 'Basic', SERVICE_OBJECTIVE = 'Basic', MAXSIZE = 1 GB) WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;
GO

ALTER DATABASE [CinderellaCore] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [CinderellaCore] SET ANSI_NULLS OFF
GO

ALTER DATABASE [CinderellaCore] SET ANSI_PADDING OFF
GO

ALTER DATABASE [CinderellaCore] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [CinderellaCore] SET ARITHABORT OFF
GO

ALTER DATABASE [CinderellaCore] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [CinderellaCore] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [CinderellaCore] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [CinderellaCore] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [CinderellaCore] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [CinderellaCore] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [CinderellaCore] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [CinderellaCore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [CinderellaCore] SET ALLOW_SNAPSHOT_ISOLATION ON
GO

ALTER DATABASE [CinderellaCore] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [CinderellaCore] SET READ_COMMITTED_SNAPSHOT ON
GO

ALTER DATABASE [CinderellaCore] SET  MULTI_USER
GO

ALTER DATABASE [CinderellaCore] SET ENCRYPTION ON
GO

ALTER DATABASE [CinderellaCore] SET QUERY_STORE = ON
GO

ALTER DATABASE [CinderellaCore] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 7), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 10, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [CinderellaCore] SET  READ_WRITE
GO